/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    HomeView: typeof import('./components/HomeView.vue')['default']
    PokemonCard: typeof import('./components/PokemonCard.vue')['default']
    PokemonDetailModal: typeof import('./components/PokemonDetailModal.vue')['default']
    PokemonTypeChipFilter: typeof import('./components/PokemonTypeChipFilter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
